package my.petshop.models;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "pets")
public class PetEntity {
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "pet_id")
	private long id;

	@NotNull
	@Column(name = "pet_name")
	private String name;
	
	@Embedded
	private Category category;

	
	
//	@OneToMany
//	@JoinColumn(name = "url")
//	private Collection<PhotoUrls> photoUrls;

	@NotNull
	@Column(name = "status")
	private String status;

	public long getId() {
		System.out.println("PET.getId will return " + id);
		return id;
	}

	public void setId(long id) {
		System.out.println("PET.setId with "+id);
		this.id = id;
	}

	public String getName() {
		System.out.println("PET.getName will return " + name);
		return name;
	}

	public void setName(String name) {
		System.out.println("PET.setName with "+name);
		this.name = name;
	}

	public String getStatus() {
		System.out.println("PET.getStatus will return " + status);
		return status;
	}

	public void setStatus(String status) {
		System.out.println("PET.setStatus with "+status);
		this.status = status;
	}

	// Public methods

	public PetEntity() {
	}

	public Category getCategory(){
		System.out.println("PET.getCategory will return " + category);
		return category;
	}
	
	public void setCategory(Category category){
		System.out.println("PET.setCategory with "+category);
		this.category = category;
	}

//	public Collection<PhotoUrls> getPhotoUrls() {
//		return photoUrls;
//	}
//
//	public void setPhotoUrls(Collection<PhotoUrls>  photoUrls) {
//		this.photoUrls = photoUrls;
//	}

//	public Collection<Tags> getTags() {
//		return tags;
//	}
//
//	public void setTags(Collection<Tags> tags) {
//		this.tags = tags;
//	}
}