package my.petshop.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.persistence.Id;

import my.petshop.common.MyConstantes;

@Entity
@Table(name = "pets")
public class PetEntity {
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	private long id;

	@NotNull
	@Column(name = "name")
	private String name;

	@NotNull
	@Column(name = "category")
	private String category;

	@NotNull
	@Column(name = "status")
	private String status;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	// Public methods

	public PetEntity() {
	}

	public PetEntity(long id) {
		this.id = id;
	}

	public PetEntity(String category, String name) {
		this.category = category;
		this.name = name;
		this.status = MyConstantes.AVAILABLE_STATUS;
	}

	public String toString() {
		return "{id=" + id + ";name=" + name + ";category=" + category + ";status=" + status + "}";
	}
}